services:
  postgres:
    image: postgres:16
    container_name: user_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-auth:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth_user_info
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

  postgres-order:
    image: postgres:16
    container_name: order_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: order_service
    ports:
      - "5434:5432"
    volumes:
      - pgdata-order:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: user_redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: user_service
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8082:8082"

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth_service
    depends_on:
      - postgres-auth
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8083:8083"

  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: order_service
    depends_on:
      - postgres-order
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: order_service
      USER_SERVICE_URL: http://user-service:8082
    ports:
      - "8084:8084"

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api_gateway
    depends_on:
      - auth-service
      - user-service
      - order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SERVICE_URL: http://auth-service:8083
      USER_SERVICE_URL: http://user-service:8082
      ORDER_SERVICE_URL: http://order-service:8084
    ports:
      - "8085:8085"

volumes:
  pgdata:
  pgdata-auth:
  pgdata-order: