spring:
  application:
    name: PaymentService-Local
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_service
      database: payment_service
  liquibase:
    change-log: classpath:db/changelog/changelog-master.json
    enabled: true

logging:
  level:
    com.innowise.paymentservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG

random-number:
  url: https://www.randomnumberapi.com/api/v1.0/random?min=1&max=100&count=1

