spring:
  application:
    name: UserService-Docker
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    com.innowise.userservice: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO