spring:
  application:
    name: OrderService-Docker
  datasource:
    url: jdbc:postgresql://postgres-order:5432/order_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.innowise.orderservice.dto.models"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.innowise.orderservice: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

user-service:
  url: ${USER_SERVICE_URL:http://user-service:8082}