name: CI Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [UserService, OrderService, PaymentService]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          mvn -B clean compile
      - name: Package JAR (PR only)
        if: github.event_name == 'pull_request'
        run: |
          cd ${{ matrix.service }}
          mvn -B clean package -DskipTests
      - name: Upload JAR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-jar
          path: ${{ matrix.service }}/target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [UserService, OrderService, PaymentService]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          if [ "${{ matrix.service }}" = "PaymentService" ]; then
            mvn -B test -Dnet.bytebuddy.experimental=true
          else
            mvn -B test
          fi

  sonarQube:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [UserService, OrderService, PaymentService]
        include:
          - service: UserService
            sonar-project-key: anna-amsht_services_userservice
          - service: OrderService
            sonar-project-key: anna-amsht_services_orderservice
          - service: PaymentService
            sonar-project-key: anna-amsht_services_paymentservice
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ${{ matrix.service }}
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ matrix.sonar-project-key }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=anna-amsht -Dsonar.token=${{ secrets.SONAR_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: sonarQube
    if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    strategy:
      matrix:
        service: [UserService, OrderService, PaymentService]
        include:
          - service: UserService
            image-name: user-service
            port: 8082
          - service: OrderService
            image-name: order-service
            port: 8084
          - service: PaymentService
            image-name: payment-service
            port: 8086
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build JAR
        run: |
          cd ${{ matrix.service }}
          mvn -B clean package -DskipTests
      - name: Set Image Tag
        id: tag
        run: |
          echo "tag=$( [ '${{ github.event_name }}' = 'pull_request' ] && echo 'pr-${{ github.event.pull_request.number }}' || echo 'latest' )-${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Build Docker Image
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image-name }}:${{ steps.tag.outputs.tag }} .
      - name: Save & Upload Docker (PR only)
        if: github.event_name == 'pull_request'
        run: |
          cd ${{ matrix.service }}
          docker save ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image-name }}:${{ steps.tag.outputs.tag }} -o image.tar
          echo "name=docker-image-${{ matrix.image-name }}-pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
        id: artifact
      - name: Upload Docker Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ matrix.service }}/image.tar
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          cd ${{ matrix.service }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image-name }}:latest-${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image-name }}:latest-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image-name }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image-name }}:latest